name: Build Typst document
on: push
permissions:
  contents: write

jobs:
  build_typst_documents:
    defaults:
      run:
        working-directory: "./easy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Font installation
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-linuxlibertine fonts-noto fonts-inconsolata
      - name: Install Typst
        uses: typst-community/setup-typst@v3
      - name: Compile main
        run: typst compile main.typ main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: easy/main.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: easy/main.pdf
