name: Build Typst document
on: push
permissions:
  contents: write

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Font installation
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-linuxlibertine fonts-noto fonts-inconsolata
      - name: Install Typst
        uses: typst-community/setup-typst@v3
      - name: Compile easy.typ
        run: typst compile easy.typ easy.pdf
      - name: Compile bigbook.typ
        run: typst compile bigbook.typ bigbook.pdf
      - name: Upload PDF files
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            easy.pdf
            bigbook.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files:
            - easy.pdf
            - bigbook.pdf
